# Generated by Django 5.2.7 on 2025-10-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='полное имя')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['created_at'],
                'permissions': [('administrator', 'редактирование автора')],
                'indexes': [models.Index(fields=['full_name'], name='authors_aut_full_na_cc4eaa_idx')],
            },
        ),
    ]
