# Generated by Django 5.2.7 on 2025-10-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'у читателя'), (2, 'в библиотеке'), (0, 'утеряна')], default=2, verbose_name='статус выдачи')),
                ('date_get', models.DateTimeField(blank=True, null=True, verbose_name='дата выдачи')),
                ('date_return', models.DateTimeField(blank=True, null=True, verbose_name='дата возврата')),
                ('book', models.ManyToManyField(related_name='книга', to='library.book', verbose_name='книга')),
            ],
            options={
                'verbose_name': 'Выдача книг',
                'verbose_name_plural': 'Выдачи книг',
                'ordering': ['reader'],
            },
        ),
    ]
